---
bolt_base_apt_dependencies: 
  - elixir
  - erlang-dev
  - erlang-eunit
  - erlang-parsetools
bolt_apt_dependencies: "{{ bolt_base_apt_dependencies + ternary(bolt_enable_rrd, ['rrdtool'], []) }}"
